alias devkit-pc-ip-address="ipconfig getifaddr en0"
alias devkit-pc-restart="sudo shutdown -r now"
alias devkit-pc-shutdown="sudo shutdown -h now"
alias devkit-zsh-reset="exec zsh"
alias devkit-bash-reset="exec bash"
