# Input Style
export GUM_INPUT_CURSOR_FOREGROUND="#FFFF0A"
export GUM_INPUT_PROMPT_FOREGROUND="#FFF"
export GUM_INPUT_WIDTH=50
export GUM_INPUT_HEADER_FOREGROUND="#FFFF0A"
export GUM_INPUT_CURSOR_FOREGROUND="#FFF"

# Choose Style
export GUM_CHOOSE_CURSOR_FOREGROUND="#FFFF0A"
export GUM_CHOOSE_ITEM_FOREGROUND="#FFF"
export GUM_CHOOSE_SELECTED_FOREGROUND="#16FDA2"
export GUM_CHOOSE_HEADER_FOREGROUND="#FFFF0A"

# Confirm Style
export GUM_CONFIRM_SELECTED_FOREGROUND="#111"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#111"
export GUM_CONFIRM_SELECTED_BACKGROUND="#FFFF0A"
export GUM_CONFIRM_UNSELECTED_BACKGROUND="#FFF"
export GUM_CONFIRM_PROMPT_FOREGROUND="#111"
export GUM_CONFIRM_PROMPT_BACKGROUND="#FFF"
export GUM_CONFIRM_PROMPT_PADDING="0 1"
export GUM_CONFIRM_PROMPT_MARGIN="1 0"
