# Input Style
export GUM_INPUT_CURSOR_FOREGROUND="#FF0"
export GUM_INPUT_PROMPT_FOREGROUND="#FFF"
export GUM_INPUT_WIDTH=80
export GUM_INPUT_HEADER_FOREGROUND="#FF0"
export GUM_INPUT_CURSOR_FOREGROUND="#FFF"

# Choose Style
export GUM_CHOOSE_CURSOR_FOREGROUND="#FF0"
export GUM_CHOOSE_ITEM_FOREGROUND="#FFF"
export GUM_CHOOSE_SELECTED_FOREGROUND="#00FF00"
export GUM_CHOOSE_HEADER_FOREGROUND="#FF0"
